name: Greeting from LAM SIU FUNG


on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:

  my-job:
    name: My Job

    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Lam
        MIDDLE_NAME: Siu
        LAST_NAME: Fung
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
